<a href="https://colab.research.google.com/github/Hibi1001/practice/blob/main/1_Numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# 1. Numpy Exercise
---

Exercise_1 : Numpyライブラリを np というエイリアスでインポートしてください

In [2]:
import numpy as np

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>import numpy as np</code>
</details>

Exercise_2 :  [1, 3, 5, ..., 21, 23] の連続する値を持つ1次元のNumpy Array（変数名 arr1）を作成してください

In [43]:
arr1 = np.arange(1, 24, 2)
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1 = np.arange(1, 24, 2)</code>
</details>

In [19]:
# 実行して表示
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

Exercise_3 : [0., 0.5, 1, ..., 5.5, 6.] （要素数は13）の連続する値を持つ1次元のNumpy Array（変数名 arr2）を作成してください

In [24]:
arr2 = np.linspace(0, 6, 13)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr2 = np.linspace(0, 6, 13)</code><br>
    <code>np.arange(0, 6.1, 0.5)</code>などでも可
</details>

In [25]:
# 実行して表示
arr2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

Exercise_4 : arr1 を3行4列の配列に変換してください(arr1_reshaped)

In [26]:
arr1_reshaped = arr1.reshape(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped = arr1.reshape(3, 4)</code>
</details>

In [27]:
# 実行して表示
arr1_reshaped

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

Exercise_5: arr1 を2次元で1列の配列に変換してください(arr1_1col)

In [34]:
arr1_1col = arr1.reshape(-1, 1)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_1col = arr1.reshape(-1, 1)</code>
</details>

In [35]:
# 実行して表示
arr1_1col

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23]])

Exercise_6 : arr1 を1次元の配列に変換してください(arr1_1dim)。ただし、arr1を扱っていく一方で、arr1_1dimの値の更新を行っていくことを前提とします。（もとのarr1のデータが変更されない手法を用いる）

In [44]:
arr1_1dim = arr1.flatten()

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_1dim = arr1.flatten()</code>
    <p>※ ravel()の場合はarr1_1dimを更新するとarr1も更新されてしまうため</p>
</details>

In [41]:
# 実行して表示
arr1_1dim

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [42]:
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

Exercise_7 : arr1_reshaped の次元数とその形状を確認してください

In [48]:
# 次元
arr1_reshaped.ndim

(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped.ndim</code>
</details>

In [49]:
# 形状
arr1_reshaped.shape

(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_reshaped.shape</code>
</details>

Exercise_8: Numpy の random モジュールを使い、0以上1未満の乱数を5つ持つ一次元の配列を作成してください（arr3）

In [62]:
arr3 = np.random.rand(5)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr3 = np.random.rand(5)</code>
</details>

In [63]:
# 実行して表示
arr3

array([0.64114679, 0.42848643, 0.26883171, 0.20676128, 0.55842386])

Exercise_9: 0以上1未満の乱数を持つ2行6列の配列を作成してください（arr4）

In [69]:
arr4 = np.random.rand(2, 6)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr4 = np.random.rand(2, 6)</code>
</details>

In [70]:
# 実行して表示
arr4

array([[0.4859232 , 0.78533092, 0.62197031, 0.97385931, 0.2532195 ,
        0.20752563],
       [0.66068013, 0.08848884, 0.12690317, 0.57475019, 0.17141745,
        0.04269776]])

Exercise_10 : 平均が 0、標準偏差が 1 で、正規分布に従う値を持つ3行4列の配列を作成してください （arr5）

In [71]:
arr5 = np.random.randn(3, 4)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr5 = np.random.randn(3, 4)</code>
</details>

In [72]:
# 実行して表示
arr5

array([[ 0.90787592, -0.95324807,  0.47418855, -1.91577023],
       [-0.08354385, -0.10879799, -0.42771096,  0.80533648],
       [ 0.75415795,  0.52715006,  0.04919288,  0.5751656 ]])

Exercise_11 : arr5 の全要素での、最大値、最小値、平均を確認してください（max_arr5, min_arr5, mean_arr5）

In [75]:
max_arr5 = arr5.max()
min_arr5 = arr5.min()
mean_arr5 = arr5.mean()
print(f'max : {max_arr5}, min : {min_arr5}, mean : {mean_arr5}')
# 各行ではなく、全体の最大などを取得していることに注意

max : 0.9078759207384507, min : -1.9157702293768086, mean : 0.05033302907225979


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>max_arr5 = arr5.max()</code><br>
    <code>min_arr5 = arr5.min()</code><br>
    <code>mean_arr5 = arr5.mean()</code>
</details>

Exercise_12: 平均が 100、標準偏差が 10 で、正規分布に従う値を持つ3行4列の配列を作成してください （arr6）

In [78]:
arr6 = np.random.normal(100, 10, (3, 4))

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr6 = np.random.normal(100, 10, (3, 4))</code>
</details>

In [79]:
# 実行して表示
arr6

array([[107.70308881, 112.0380401 , 106.72411027, 107.87041047],
       [107.99626097, 106.73473235,  94.90281201, 107.51157379],
       [ 98.18041419,  82.89211406, 100.42533802,  86.8721472 ]])

Exercise_13 : 10 以上 30 未満の値を持つ連続一様分布の3行4列の配列を作成してください （arr7）。また要素全体の平均値が20付近にあることを平均値を求めることで確認してください。

In [90]:
arr7 = np.random.uniform(10, 30, (3, 4))

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr7 = np.random.uniform(10, 30, (3, 4))</code>
</details>

In [91]:
# 実行して表示
arr7

array([[12.18411628, 18.70527483, 13.24135735, 13.72840945],
       [29.42664505, 23.74835704, 17.30041925, 28.18837669],
       [15.06342698, 18.27457726, 15.13622594, 19.50199142]])

In [92]:
# 平均値を求める
arr7.mean()
# 20前後の値ならばOK

18.708264796712356

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr7.mean()</code>
</details>

Exercise_14 : arr7 の数値をすべて小数第4位で四捨五入した小数3桁の値に変換してください(arr7_3decimal)

In [94]:
arr7_3decimal = np.round(arr7, 3)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr1_3decimal = np.round(arr7, 3)</code>
</details>

In [95]:
# 実行して表示
arr7_3decimal

array([[12.184, 18.705, 13.241, 13.728],
       [29.427, 23.748, 17.3  , 28.188],
       [15.063, 18.275, 15.136, 19.502]])

Exercise_15: リスト lis の文字をランダムに10個持つ1次元の配列を作成し（arr8）、データタイプを object に変更してください

In [ ]:
# リストを作成
lis = list('GOOD!')   # ['G', 'O', 'O', 'D', '!']
arr8 =

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr8 = np.random.choice(lis, 10)</code>
</details>

In [ ]:
# 実行して表示
arr8

In [ ]:
# データタイプを変更
arr8 =

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr8 = arr8.astype(object)</code>
</details>

In [ ]:
# 実行して表示
arr8

Exercise_16 : 次のarr9のデータタイプが 'int32' であることを確認し、その後データタイプを 'float' に変更してください

In [ ]:
# dtypeの確認
arr9 = np.array([1, 3, 5, 7, 9])


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr9.dtype</code>
</details>

In [ ]:
# floatに変更
arr9 =

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr9.astype(float)</code><br>
</details>

In [ ]:
# 実行して表示
arr9

Exercise_17 : 配列arr10の分散と標準偏差を「計算して」求めてください。また、メソッドを用いてその値が正しいことを確認してください。

In [ ]:
# 実行して表示
np.random.seed(17)
arr10 = np.random.randint(0, 10, 5)
arr10

In [ ]:
# 実行して表示
mean = arr10.mean()
mean

In [ ]:
total = 0
for i in arr10:
    total +=
total

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>total += (i - mean)**2</code><br>
</details>

In [ ]:
variance =
# 実行して表示
variance

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>variance = total / len(arr10)</code><br>
</details>

In [ ]:
standard_deviation =
# 実行して表示
standard_deviation

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>standard_deviation = np.sqrt(variance)</code><br>
</details>

In [ ]:
# メソッドを使って分散を求める


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr10.var()</code><br>
</details>

In [ ]:
# メソッドを使って標準偏差を求める


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr10.std()</code><br>
</details>

## 以上